from .assistant_prompts import SHOPPING_ASSISTANT_SYSTEM_PROMPT, INTENT_EXTRACTION_PROMPT
from .domain_prompts import (
    SEMANTIC_SEARCH_SYSTEM_PROMPT,
    SCENT_FINDER_PROMPT,
    RECOMMENDATION_PROMPT,
    SUPPORT_SYSTEM_PROMPT
)

__all__ = [
    "SHOPPING_ASSISTANT_SYSTEM_PROMPT",
    "INTENT_EXTRACTION_PROMPT",
    "SEMANTIC_SEARCH_SYSTEM_PROMPT",
    "SCENT_FINDER_PROMPT",
    "RECOMMENDATION_PROMPT",
    "SUPPORT_SYSTEM_PROMPT"
]
